#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const CORE_DIR = path.join(ROOT, "core");
const MODS_DIR = path.join(ROOT, "mods");
const DIST_DIR = path.join(ROOT, "dist");
const OUT_FILE = path.join(DIST_DIR, "blackettweaks.js");

const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8"));

function indent(code, spaces = 4) {
    const pad = " ".repeat(spaces);
    return code
        .split("\n")
        .map((line) => (line.trim() === "" ? "" : pad + line))
        .join("\n");
}

function readModule(filePath) {
    return fs.readFileSync(filePath, "utf8").replace(/\s+$/, "");
}

const bootstrap = readModule(path.join(CORE_DIR, "bootstrap.js"));
const settingsPanel = readModule(path.join(CORE_DIR, "settings-panel.js"));

const modFiles = fs
    .readdirSync(MODS_DIR)
    .filter((name) => name.endsWith(".js"))
    .sort();

const mods = modFiles.map((name) => readModule(path.join(MODS_DIR, name)));

const header = `// ==UserScript==
// @name         BlacketTweaks
// @namespace    blackettweaks
// @version      ${pkg.version}
// @description  Adds quality-of-life features to Blacket (private server friendly).
// @match        *://*/*
// @run-at       document-idle
// @grant        none
// ==/UserScript==

// Generated by build.js from core/ and mods/ — do not edit this file directly.
`;

const sections = [bootstrap, ...mods, settingsPanel].map((code) => indent(code));

const body = ["(function () {", sections.join("\n\n"), "})();"].join("\n");

fs.mkdirSync(DIST_DIR, { recursive: true });
fs.writeFileSync(OUT_FILE, `${header}\n${body}\n`, "utf8");

console.log(`Built dist/blackettweaks.js from ${modFiles.length} mod(s): ${modFiles.join(", ")}`);
